runtime: python39
entrypoint: gunicorn -b :$PORT  Website:app

instance_class: F2

env_variables:
  CLOUD_STORAGE_BUCKET: "urlsigner"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

handlers:
- url: /static
  static_dir: static/

- url: /.*
  script: auto

runtime_config:
  python_version: 3.9
